import 'naming.dart';

class GeneratedIcon {
  GeneratedIcon({
    required this.identifier,
    required this.ligature,
    required this.codepoint,
  });
  final String identifier;
  final String ligature;
  final int codepoint;
}

/// Builds the final Dart source for an icon-font class.
String emitDartSource({
  required String familyName,
  required Iterable<({String ligature, int codepoint})> entries,
}) {
  final sortedEntries = entries.toList()
    ..sort((a, b) => a.ligature.compareTo(b.ligature));
  final rawNames = sortedEntries
      .map((e) => toIcnIdentifier(e.ligature))
      .toList();
  final identifiers = deduplicate(rawNames);

  final icons = <GeneratedIcon>[
    for (var i = 0; i < sortedEntries.length; i++)
      GeneratedIcon(
        identifier: identifiers[i],
        ligature: sortedEntries[i].ligature,
        codepoint: sortedEntries[i].codepoint,
      ),
  ];

  final className = familyName;
  final buf = StringBuffer();
  buf
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln('// Generated by package:icon_font_extractor.')
    ..writeln('// Source font family: $familyName')
    ..writeln()
    ..writeln(
      '// ignore_for_file: constant_identifier_names, non_constant_identifier_names',
    )
    ..writeln()
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln()
    ..writeln('@staticIconProvider')
    ..writeln('abstract final class $className {')
    ..writeln('  $className._();')
    ..writeln();
  for (final icon in icons) {
    final hex = icon.codepoint.toRadixString(16).toUpperCase().padLeft(4, '0');
    buf
      ..writeln('  /// Ligature: `${_escapeForDocComment(icon.ligature)}`')
      ..writeln(
        "  static const IconData ${icon.identifier} = "
        "IconData(0x$hex, fontFamily: '$familyName');",
      )
      ..writeln();
  }
  buf.writeln('}');
  return buf.toString();
}

String _escapeForDocComment(String s) =>
    s.replaceAll(r'\', r'\\').replaceAll('`', r'\`');
