import 'package:flutter/material.dart';

// Generated by `icon_font_extractor generate` from the
// MaterialIcons font asset declared in pubspec.yaml.
import 'material_icons.g.dart';

void main() => runApp(const ExampleApp());

class ExampleApp extends StatelessWidget {
  const ExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'icon_font_extractor example',
      home: Scaffold(
        appBar: AppBar(title: const Text('icon_font_extractor')),
        body: GridView.count(
          crossAxisCount: 4,
          padding: const EdgeInsets.all(16),
          children: const [
            // Use the generated `IconData` constants directly with Flutter's
            // built-in `Icon` widget — no extra wrapper required.
            Icon(MaterialIcons.icnHomeBaseline, size: 48),
            Icon(MaterialIcons.icnSearchBaseline, size: 48),
            Icon(MaterialIcons.icnSettingsBaseline, size: 48),
            Icon(MaterialIcons.icnFavoriteBaseline, size: 48),
          ],
        ),
      ),
    );
  }
}
